In [44]:
import pandas as pd
from session import Session, Track
import sys
from time import sleep

In [49]:
ses = Session('./text.txt')
t = (ses.track['REF (Stereo)'])
df = t.data
df

    channel  event  ...     duration    state
0         1      1  ...  00:00:29:07  Unmuted
1         1      2  ...  00:04:16:22  Unmuted
2         1      3  ...  00:03:00:20  Unmuted
3         1      4  ...  00:03:01:20  Unmuted
4         1      5  ...  00:02:38:16  Unmuted
5         1      6  ...  00:03:15:08  Unmuted
6         1      7  ...  00:02:54:12  Unmuted
7         1      8  ...  00:02:10:07  Unmuted
8         1      9  ...  00:03:08:08  Unmuted
9         1     10  ...  00:04:22:14  Unmuted
10        1     11  ...  00:03:45:01  Unmuted
11        1     12  ...  00:04:29:23  Unmuted
12        1     13  ...  00:02:58:02  Unmuted
13        1     14  ...  00:03:31:03  Unmuted
14        1     15  ...  00:02:49:00  Unmuted
15        1     16  ...  00:04:11:10  Unmuted
16        1     17  ...  00:03:23:03  Unmuted
17        1     18  ...  00:03:26:00  Unmuted
18        1     19  ...  00:04:38:09  Unmuted
19        1     20  ...  00:03:25:20  Unmuted
20        1     21  ...  00:00:16:23  Unmuted

[21 rows x 7 columns]

In [51]:
df[['start_time','end_time']]

     start_time     end_time
0   01:06:17:05  01:06:46:13
1   01:06:46:13  01:11:03:11
2   01:11:03:11  01:14:04:08
3   01:14:04:08  01:17:06:05
4   01:17:06:05  01:19:44:21
5   01:19:44:21  01:23:00:05
6   01:23:00:05  01:25:54:18
7   01:25:54:18  01:28:05:02
8   01:28:05:02  01:31:13:10
9   01:31:13:10  01:35:36:01
10  01:35:36:01  01:39:21:03
11  01:39:21:03  01:43:51:03
12  01:43:51:03  01:46:49:05
13  01:46:49:05  01:50:20:09
14  01:50:20:09  01:53:09:10
15  01:53:09:10  01:57:20:20
16  01:57:20:20  02:00:44:00
17  02:00:44:00  02:04:10:00
18  02:04:10:00  02:08:48:10
19  02:08:48:10  02:12:14:06
20  02:12:14:06  02:12:31:05

In [58]:
df = pd.read_excel('./test.xlsx')
print(df.columns)
df[['Unnamed: 2', 'Unnamed: 3']]

Index(['Table 1', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='object')

     Unnamed: 2   Unnamed: 3
0   01:06:17:05  01:06:46:13
1   01:06:46:13  01:11:03:11
2   01:11:03:11  01:14:04:08
3   01:14:04:08  01:17:06:05
4   01:17:06:05  01:19:44:21
5   01:19:44:21  01:23:00:05
6   01:23:00:05  01:25:54:18
7   01:25:54:18  01:28:05:02
8   01:28:05:02  01:31:13:10
9   01:31:13:10  01:35:36:01
10  01:35:36:01  01:39:21:03
11  01:39:21:03  01:43:51:03
12  01:43:51:03  01:46:49:05
13  01:46:49:05  01:50:20:09
14  01:50:20:09  01:53:09:10
15  01:53:09:10  01:57:20:20
16  01:57:20:20  02:00:44:00
17  02:00:44:00  02:04:10:00
18  02:04:10:00  02:08:48:10
19  02:08:48:10  02:12:14:06
20  02:12:14:06  02:12:31:05

In [60]:
def _progress(a,b):
    sys.stdout.write('\r')
    p_a, p_b = (a/b)*30, (1-(a/b))*30
    p_ai = int(p_a)
    p_bi = int(p_b) + 1
    
    sys.stdout.write('*'*p_ai+ '-' * p_bi)  
    sys.stdout.flush()
    
    
    
    
    
_progress(7,11)
_progress(9,11)

************************------

In [61]:
for i in range(151):
    _progress(i,150)
    sleep(.05)

******************************-